### ISSUE TITLE
panic: Failed to load device settings

### ISSUE THREAD

**Issue by petaflot** [colinrgodsey/step-daemon#26]
It's all in the title. Firmware was updated just before with the required options.

Anything I should test?

AFAIK the absence of `pages_ready` is because of CDC serial hardware

```
$ cat print.gcode | go run ./cmd/stepd -device /dev/ttyACM0 -baud 1000000 -config ./config.hjson | grep -v "ok"
info:generating bed level function...
info:config processed
info:bed level z-func loaded
wait
wait
no page_ready seen, sending anyways
info:gathering device settings
info:stepd initialized
pages_ready
echo:; Linear Units:
echo:  G21 ; (mm)
echo:; Temperature Units:
echo:  M149 C ; Units in Celsius
echo:; Filament settings (Disabled):
echo:  M200 S0 D1.7500
echo:; Steps per unit:
echo:  M92 X80.0000 Y80.0000 Z400.0000 E690.0000
echo:; Max feedrates (units/s):
info:max vel (step limit) is [2304 2304 460.8 267.1304347826087]
echo:  M203 X200.0000 Y180.0000 Z40.0000 E6.0000
echo:; Max Acceleration (units/s2):
echo:  M201 X7000.0000 Y6000.0000 Z200.0000 E6000.0000
echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
echo:  M204 P3000.0000 R7200.0000 T3000.0000
echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_jerk> Y<max_jerk> Z<max_jerk> E<max_jerk>):
echo:  M205 B20000.0000 S0.0000 T0.0000 X1.0000 Y1.0000 Z0.3000 E2.0000
echo:; Home offset:
echo:  M206 X0.0000 Y0.0000 Z0.0000
echo:; Auto Bed Leveling:
echo:  M420 S0 Z5.0000 ; Leveling OFF
echo:; Z Auto-Align:
echo:  M422 S1 X-155.0000 Y0.0000
echo:  M422 S2 X127.0000 Y0.0000
echo:; Bed PID:
echo:  M304 P103.7845 I18.5329 D387.4622
echo:; Retract (S<length> F<feedrate> Z<lift>):
echo:  M207 S2.0000 W13.0000 F2700.0000 Z1.5000
echo:; Recover (S<length> F<feedrate>):
echo:  M208 S-0.5000 W0.0000 F4800.0000
echo:; Auto-Retract (S<enable>):
echo:  M209 S0
echo:; Z-Probe Offset:
echo:  M851 X-28.0000 Y0.0000 Z-0.3000 ; (mm)
echo:; Stepper driver current:
echo:  M906 X800 Y800 Z800
echo:  M906 I1 Z800
echo:; Driver stepping mode:
echo:  M569 S1 X Y Z
echo:  M569 S1 I1 Z
echo:; Filament runout sensor:
echo:  M412 S1 ; Sensor ON
echo:; Model predictive control:
echo:  M306 E0 P40.00 C16.70 R0.2200 A0.0680 F0.0970 H0.0056
wait
panic: Failed to load device settings

goroutine 37 [running]:
main.stepdPipeline.ConfigHandler.func1({0x400011e240?, 0x400011e1e0?}, {0x400011e2a0?, 0x400011e300?})
        /home/whale/_git/step-daemon/lib/pipeline/config_handler.go:178 +0x358
created by main.handler in goroutine 1
        /home/whale/_git/step-daemon/cmd/stepd/main.go:41 +0xe0
exit status 2
```

**Comment by petaflot** [comment]
```
(py311) meta@gentx ~/_git/marlin/Marlin/Marlin $ grep -e "#define DIRECT_STEPPING" -e "#define ADVANCED_OK" -e "#define LIN_ADVANCE" Configuration_adv.h
//#define LIN_ADVANCE
#define DIRECT_STEPPING
#define ADVANCED_OK
(py311) meta@gentx ~/_git/marlin/Marlin/Marlin $ grep -e "#define AUTO_BED_LEVELING_BILINEAR" Configuration.h
#define AUTO_BED_LEVELING_BILINEAR
(py311) meta@gentx ~/_git/marlin/Marlin/Marlin $ grep "#define STEPPER_PAGE_FORMAT" src/inc/Conditionals_adv.h
    #define STEPPER_PAGE_FORMAT SP_4x2_256
```
